version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: fast_azure_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-mongo}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast_azure_backend
    ports:
      - "8000:80"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost:5173}
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo_data:


