apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fastazure
  labels:
    app: frontend
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: <ACR_LOGIN_SERVER>/fastazure-frontend:latest  # Replace with your ACR
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: fastazure-config
              key: VITE_API_BASE_URL
        - name: VITE_AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: fastazure-secrets
              key: azure-client-id
              optional: true
        - name: VITE_AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: fastazure-secrets
              key: azure-tenant-id
              optional: true
        - name: VITE_AZURE_API_SCOPE
          valueFrom:
            secretKeyRef:
              name: fastazure-secrets
              key: azure-api-scope
              optional: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fastazure
  labels:
    app: frontend
spec:
  type: LoadBalancer  # Exposes frontend externally
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend

