# ============================================
# Secrets Template
# ============================================
# DO NOT commit actual secrets to Git!
# Create secrets with kubectl:
#
# kubectl create secret generic fastazure-secrets \
#   --namespace=fastazure \
#   --from-literal=mongodb-uri='mongodb+srv://...' \
#   --from-literal=azure-client-id='your-client-id' \
#   --from-literal=azure-tenant-id='your-tenant-id' \
#   --from-literal=azure-api-scope='api://your-app-id/access_as_user'
#
# Or use this template and apply after base64 encoding values:
# echo -n 'your-value' | base64
#
apiVersion: v1
kind: Secret
metadata:
  name: fastazure-secrets
  namespace: fastazure
type: Opaque
data:
  # Base64 encoded values
  # mongodb-uri: <base64-encoded-connection-string>
  # azure-client-id: <base64-encoded-client-id>
  # azure-tenant-id: <base64-encoded-tenant-id>
  # azure-api-scope: <base64-encoded-scope>

